import yfinance as yf
import pandas as pd
import numpy as np
import QuantLib as ql
from datetime import date, timedelta
import os

class MarketScraper:
    def __init__(self, tickers=['^GSPC', '^NDX'], start_date='2010-01-01', end_date=None):
        self.tickers = tickers
        self.start_date = start_date
        self.end_date = end_date
        self.data = None

    def download_data(self):
        cache_path = 'data/raw_market_data.parquet'
        if os.path.exists(cache_path):
            print(f"Loading cached data from {cache_path}...")
            try:
                cached_data = pd.read_parquet(cache_path)

                # Check if all tickers are present
                # yfinance MultiIndex: (Ticker, PriceType) -> level 0 is Ticker
                if isinstance(cached_data.columns, pd.MultiIndex):
                    existing_tickers = cached_data.columns.levels[0]
                else:
                    # Single ticker case or flat columns?
                    # If flat and generated by yf.download(group_by='ticker'), it might be tricky.
                    # But usually it's MultiIndex for >1 ticker.
                    # If single ticker, columns might just be PriceTypes.
                    # Let's assume if we ask for multiple, we want MultiIndex.
                    existing_tickers = []

                missing = [t for t in self.tickers if t not in existing_tickers]

                if not missing:
                    self.data = cached_data
                    return self.data
                else:
                    print(f"Cache missing tickers: {missing}. Re-downloading all...")
            except Exception as e:
                print(f"Error reading cache: {e}. Re-downloading...")

        print(f"Downloading data for {self.tickers}...")
        data = yf.download(self.tickers, start=self.start_date, end=self.end_date, group_by='ticker')

        # Save to cache
        os.makedirs('data', exist_ok=True)
        data.to_parquet(cache_path)

        self.data = data
        return data

    def process_data(self):
        if self.data is None:
            self.download_data()

        processed_dfs = []

        # Check if columns are MultiIndex (Ticker, PriceType)
        is_multi = isinstance(self.data.columns, pd.MultiIndex)

        for ticker in self.tickers:
            try:
                if is_multi:
                    df = self.data[ticker].copy()
                else:
                    # If only one ticker, yfinance might not return MultiIndex
                    if ticker == self.tickers[0] and len(self.tickers) == 1:
                        df = self.data.copy()
                    else:
                        # Fallback or error
                        print(f"Warning: Structure unclear for {ticker}")
                        continue

                # Calculate Log Returns
                # Handle missing data
                if df.empty:
                    print(f"Warning: Empty data for {ticker}")
                    continue

                df['LogReturn'] = np.log(df['Close'] / df['Close'].shift(1))
                # Calculate Realized Volatility (21-day rolling std dev of log returns)
                df['RealizedVol'] = df['LogReturn'].rolling(window=21).std() * np.sqrt(252)

                df = df.dropna()
                df['Ticker'] = ticker
                processed_dfs.append(df)
            except KeyError:
                print(f"Warning: Could not process {ticker}")
                continue

        if not processed_dfs:
            raise ValueError("No data processed!")

        combined_df = pd.concat(processed_dfs)
        return combined_df

class HestonSimulator:
    def __init__(self, risk_free_rate=0.03):
        self.risk_free_rate = risk_free_rate
        self.day_count = ql.Actual365Fixed()
        self.calendar = ql.UnitedStates(ql.UnitedStates.NYSE)

    def generate_surface(self, spot_price, v0, kappa=2.0, theta=0.04, sigma=0.3, rho=-0.7):
        """
        Generates option prices for a grid of maturities and moneyness using the Heston model.
        """
        today = date.today()
        ql_date = ql.Date(today.day, today.month, today.year)
        ql.Settings.instance().evaluationDate = ql_date

        # Heston Process
        # v0: initial variance
        # kappa: mean reversion speed
        # theta: long-term variance
        # sigma: volatility of volatility
        # rho: correlation between spot and vol

        # Ensure parameters are within valid ranges
        v0 = max(v0, 1e-4)
        theta = max(theta, 1e-4)

        flat_ts = ql.YieldTermStructureHandle(ql.FlatForward(ql_date, self.risk_free_rate, self.day_count))
        dividend_ts = ql.YieldTermStructureHandle(ql.FlatForward(ql_date, 0.0, self.day_count))
        spot_handle = ql.QuoteHandle(ql.SimpleQuote(spot_price))

        heston_process = ql.HestonProcess(flat_ts, dividend_ts, spot_handle, v0, kappa, theta, sigma, rho)
        heston_model = ql.HestonModel(heston_process)
        engine = ql.AnalyticHestonEngine(heston_model)

        maturities_months = [1, 3, 6]
        moneyness_levels = [0.8, 0.9, 0.95, 1.0, 1.05, 1.1, 1.2]

        surface_data = []

        for m in maturities_months:
            maturity_date = ql_date + ql.Period(m, ql.Months)
            # Ensure maturity is a business day
            maturity_date = self.calendar.adjust(maturity_date)

            time_to_maturity = self.day_count.yearFraction(ql_date, maturity_date)

            for k_ratio in moneyness_levels:
                strike_price = spot_price * k_ratio

                # Option type: Call
                payoff = ql.PlainVanillaPayoff(ql.Option.Call, strike_price)
                exercise = ql.EuropeanExercise(maturity_date)
                option = ql.VanillaOption(payoff, exercise)

                option.setPricingEngine(engine)

                try:
                    price = option.NPV()
                    # Normalize price by spot? Or keep raw?
                    # Keeping raw for now, but usually normalized price (Price/Spot) is better for ML
                    normalized_price = price / spot_price
                except Exception as e:
                    print(f"Error pricing option: {e}")
                    normalized_price = 0.0

                surface_data.append({
                    'Maturity': time_to_maturity,
                    'Moneyness': k_ratio,
                    'Price': normalized_price,
                    'Strike': strike_price
                })

        return surface_data

def generate_dataset(tickers=['^GSPC', '^NDX', '^RUT', '^DJI'], output_path='data/processed_dataset.parquet'):
    print(f"Initializing Scraper for {tickers}...")
    scraper = MarketScraper(tickers=tickers)
    market_data = scraper.process_data()

    print("Initializing Heston Simulator...")
    simulator = HestonSimulator()

    dataset_rows = []

    for ticker in tickers:
        print(f"Processing {ticker}...")
        if ticker not in market_data['Ticker'].values:
            print(f"Warning: No data found for {ticker}")
            continue

        ticker_data = market_data[market_data['Ticker'] == ticker].sort_index()
        print(f"Generating surfaces for {len(ticker_data)} days of {ticker}...")

        for date_idx, row in ticker_data.iterrows():
            spot = row['Close']
            realized_vol = row['RealizedVol']

            # Heuristic: Map realized vol to Heston parameters
            v0 = realized_vol ** 2

            # Stable parameters
            kappa = 2.0
            theta = v0
            sigma = 0.3
            rho = -0.7

            surface = simulator.generate_surface(spot, v0, kappa, theta, sigma, rho)

            flat_prices = []
            for point in surface:
                flat_prices.append(point['Price'])

            # Check history
            loc_idx = ticker_data.index.get_loc(date_idx)
            if loc_idx < 30:
                continue

            past_30_days = ticker_data.iloc[loc_idx-30:loc_idx]

            input_returns = past_30_days['LogReturn'].values
            input_vols = past_30_days['RealizedVol'].values

            row_dict = {
                'Date': date_idx,
                'Ticker': ticker,
                'Spot': spot,
                'RealizedVol': realized_vol,
                'Input_Returns': input_returns,
                'Input_Vols': input_vols,
                'Target_Prices': np.array(flat_prices),
                'Heston_Params': {'kappa': kappa, 'theta': theta, 'sigma': sigma, 'rho': rho, 'v0': v0}
            }
            dataset_rows.append(row_dict)

            if len(dataset_rows) % 500 == 0:
                print(f"Processed {len(dataset_rows)} samples...")

    print("Saving dataset...")
    df_final = pd.DataFrame(dataset_rows)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    df_final.to_parquet(output_path)
    print(f"Dataset saved to {output_path} with {len(df_final)} samples.")

if __name__ == "__main__":
    generate_dataset()
